### PR TITLE
Support for armhf more than armv7

### PR DESCRIPTION
**Pull request by rosbeef**
## Problem

error : Failed to provision sources : In resources.sources: it looks like you forgot to define url/sha256 or armhf.url/armhf.sha256

## Solution

add armhf.url line with the same armv7 url source in the manifestt.toml

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
i don't understand your problem

this package doesn't have an `armhf` source because because it distinguishes armv6 and armv7

**Comment by rosbeef** [comment]
In [Debian](https://en.wikipedia.org/wiki/Debian) [Linux](https://en.wikipedia.org/wiki/Linux) and derivatives such as [Ubuntu](https://en.wikipedia.org/wiki/Ubuntu) and [Linux Mint](https://en.wikipedia.org/wiki/Linux_Mint), armhf (ARM hard float) refers to the ARMv7 architecture

source https://en.wikipedia.org/wiki/ARM_architecture_family

**Comment by OniriCorpe** [comment]
AFAIK the yunohost default detection returns `armhf` for both `armv6` and `armv7`
see: https://github.com/YunoHost-Apps/gotosocial_ynh/blob/master/scripts/_common.sh#L12

**Comment by rosbeef** [comment]
Here it is.
https://paste.yunohost.org/raw/cakalufuyi

The ynh_setup_source is using "dpkg --print-architecture" to detect arch (https://yunohost.org/en/packaging_apps_resources#sources)
which return armhf for my armv7l arch. odroidxu4.

Maybe here is the difference.
j;)

**Pull request merged**
