### PR TITLE
Update config_panel.toml: fix stupid toml parsing issue for foo.bar = '''content'''' with multi-line content (breaking bookworm)

### PR DESCRIPTION
**Pull request by alexAubin**

### CODE REVIEW

**Comment by alexAubin** [comment]
!bookwormtestme

**Comment by OniriCorpe** [comment]
```text
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 77, in <module>
    yunohost.cli(
  File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
    ret = moulinette.cli(
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 115, in cli
    ).run(args, output_as=output_as, timeout=timeout)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 501, in run
    ret = self.actionsmap.process(args, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 567, in process
    return func(**arguments)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 1815, in app_config_get
    return config_.get(key, mode)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 464, in get
    self.config, self.form = self._get_config_panel(prevalidate=False)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 791, in _get_config_panel
    config = ConfigPanelModel(**raw_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 300, in __init__
    super().__init__(version=version, i18n=i18n, panels=panels)
  File "/usr/lib/python3/dist-packages/pydantic/main.py", line 342, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 3 validation errors for ConfigPanelModel
panels -> 0 -> sections -> 4 -> options -> 4 -> EmailOption -> default
  value is not a valid email address (type=value_error.email)
panels -> 0 -> sections -> 4 -> options -> 5 -> SelectOption -> en
  extra fields not permitted (type=value_error.extra)
panels -> 0 -> sections -> 4 -> options -> 5 -> SelectOption -> fr
  extra fields not permitted (type=value_error.extra)
```

:/

**Comment by OniriCorpe** [comment]
```text
panels -> 0 -> sections -> 4 -> options -> 4 -> EmailOption -> default
  value is not a valid email address (type=value_error.email)
```

`default = "GoToSocial@__DOMAIN__"` eeeeh ...

**Comment by OniriCorpe** [comment]
!bookwormtestme

**Comment by alexAubin** [comment]
>`default = "GoToSocial@__DOMAIN__"` eeeeh ...

ugh x_x Are you sure `__DOMAIN__` gets replaced in that context tho ?

**Comment by OniriCorpe** [comment]
don't know 🙃

**Comment by OniriCorpe** [comment]
!testme

**Pull request merged**
