### PR TITLE
Testing v0.7.1 Even Stormier Sloth

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Problem

- v0.7.0 is bugged so unusable for ynh users
- the bug will be fixed in v0.7.1

## Solution

- preparing for v0.7.1 using the changes introduced in the v0.7.0
- ~~#61~~

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
⚠️ this PR is waiting for the v0.7.1 release

**Comment by lapineige** [comment]
Don't forget to changed package version :)

**Comment by OniriCorpe** [comment]
> Don't forget to change package version :)

the bot will do it by itself in its PR ^w^

**Comment by lapineige** [comment]
Oh I forgot this ! 😁

**Comment by OniriCorpe** [comment]
Implementing #61

!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
meh, the 'account_domain' stuff was breaking the CI tests
I think I finally managed to trick the CI into passing but big sigh 😫

**Comment by OniriCorpe** [comment]
!testme

**Comment by lapineige** [comment]
:rocket:

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
🎉

**Comment by PrivacyDragon** [comment]
Woohoo!

**Comment by lapineige** [comment]
Well done !

**Pull request merged**
