### PR TITLE
Testing v0.11.0 Sloppy Sloth

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Problem

- #92
Changelog: https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.11.0

## Solution

- [x] Upgrade package
- [x] Updating config file
- [x] Implementing new config parameters in the config panel

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
all right 😌

**Comment by lapineige** [comment]
Thank you !

**Pull request merged**
